version: "3.8"

services:
  broker:
    image: fiware/orion-ld
    platform: linux/amd64
    hostname: orion
    command:
      - "-dbhost"
      - mongo
    ports:
      - "1026:1026"
    depends_on:
      - mongo
      - quantumleap
    networks:
      - fiware_part1
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    networks:
      - fiware_part1
  crate-db:
    image: amd64/crate:4.1.4
    hostname: crate-db
    ports:
      - "4200:4200"
      - "4300:4300"
    command:
      crate -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true
      -Chttp.cors.allow-origin="*"
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - fiware_part1
  quantumleap:
    image: orchestracities/quantumleap
    hostname: quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db
      - LOGLEVEL=DEBUG
    healthcheck:
      test: curl --fails -s http://quantumleap:8668/version || exit 1
    networks:
      - fiware_part1
  parking_simulation:
    build: ./parking_simulation
    environment:
      - BROKER_HOSTNAME=orion
    depends_on:
      - broker
    networks:
      - fiware_part1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
  water_simulation:
    build: ./water_simulation
    environment:
      - BROKER_HOSTNAME=orion
    depends_on:
      - broker
    networks:
      - fiware_part1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
  grafana:
    image: grafana/grafana
    depends_on:
      - crate-db
    ports:
      - "3003:3000"
    networks:
      - fiware_part1
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/orchestracities/map-panel/releases/download/v1.4.4/orchestracities-map-panel-1.4.4.zip;grafana-clock-panel,grafana-worldmap-panel
networks:
  fiware_part1: {}
