services:
  context_broker:
    image: fiware/orion:latest
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo-db:27017

  mongo-db:
    image: mongo:4.4
    ports:
      - "27017:27017"

  quantumleap:
    image: smartsdk/quantumleap:latest
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate-db

  crate-db:
    image: crate:latest
    ports:
      - "4200:4200"
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
