version: '3.8'

services:
  context_broker:
    image: fiware/orion:latest
    ports:
      - "1026:1026"
    command: -dbhost mongo-db

  mongo-db:
    image: mongo:4.4
    ports:
      - "27017:27017"

  quantumleap:
    image: fiware/quantumleap:latest
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate-db

  crate-db:
    image: crate:latest
    ports:
      - "4200:4200"
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
